FROM node:18-alpine 

WORKDIR /app

# stop nextjs from collecting telemetry data 
#ENV NEXT_TELEMETRY_DISABLED 1

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./

RUN npm install

COPY . .

EXPOSE 5173

CMD npm run dev
