FROM python:3.9-slim-bookworm

#ENV FLASK_APP=borrowhood

WORKDIR /app

COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . /app

EXPOSE 8000

#CMD ["fastapi", "dev", "main.py"]
CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --loop asyncio"]

